[package]
name = "axconfig-macros"
description = "Procedural macros for converting TOML format configurations to Rust constant definitions."
documentation = "https://docs.rs/axconfig-macros"
categories = ["development-tools::procedural-macro-helpers", "config", "parsing", "parser-implementations"]
keywords.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
nightly = []

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
axconfig-gen = { path = "../axconfig-gen", version = "0.2" }

[lib]
proc-macro = true
